import { Canvas } from '@react-three/fiber'
import { OrbitControls } from '@react-three/drei'

function WoundModel() {
  return (
    <mesh rotation={[0, 0, 0]}>
      {/*
        Using a simple plane with displacement map for the demo.
        Real implementation uses a .obj mesh generated by the Python backend.
        We don't have the backend running on Vercel so this is fine.
      */}
      <planeGeometry args={[3, 3, 64, 64]} />
      <meshStandardMaterial
        color="#e5e7eb"
        wireframe
        wireframeLinewidth={1.5}
      />
      <ambientLight intensity={0.5} />
      <pointLight position={[10, 10, 10]} />
    </mesh>
  )
}

export default function Wound3DViewer() {
  return (
    <div className="w-full h-full min-h-[300px]">
      <Canvas camera={{ position: [2, 2, 2] }}>
        <color attach="background" args={['#F9FBFD']} />
        <OrbitControls autoRotate autoRotateSpeed={0.5} enableZoom={false} />
        <WoundModel />
        <gridHelper args={[10, 10, 0xe5e7eb, 0xe5e7eb]} />
      </Canvas>
    </div>
  )
}
